# Form implementation generated from reading ui file 'add.ui'
#
# Created by: PyQt6 UI code generator 6.8.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(586, 403)
        MainWindow.setStyleSheet("background-color: rgb(255, 238, 226);")
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.nameEdit = QtWidgets.QLineEdit(parent=self.centralwidget)
        self.nameEdit.setGeometry(QtCore.QRect(80, 60, 451, 20))
        self.nameEdit.setText("")
        self.nameEdit.setObjectName("nameEdit")
        self.shelterEdit = QtWidgets.QLineEdit(parent=self.centralwidget)
        self.shelterEdit.setGeometry(QtCore.QRect(80, 100, 451, 20))
        self.shelterEdit.setObjectName("shelterEdit")
        self.breedEdit = QtWidgets.QLineEdit(parent=self.centralwidget)
        self.breedEdit.setGeometry(QtCore.QRect(80, 140, 451, 20))
        self.breedEdit.setObjectName("breedEdit")
        self.ageEdit = QtWidgets.QLineEdit(parent=self.centralwidget)
        self.ageEdit.setGeometry(QtCore.QRect(80, 180, 451, 20))
        self.ageEdit.setObjectName("ageEdit")
        self.add = QtWidgets.QPushButton(parent=self.centralwidget)
        self.add.setGeometry(QtCore.QRect(100, 300, 75, 23))
        self.add.setObjectName("add")
        self.back = QtWidgets.QPushButton(parent=self.centralwidget)
        self.back.setGeometry(QtCore.QRect(380, 300, 75, 23))
        self.back.setObjectName("back")
        self.add_photo = QtWidgets.QPushButton(parent=self.centralwidget)
        self.add_photo.setGeometry(QtCore.QRect(84, 220, 451, 23))
        self.add_photo.setObjectName("add_photo")
        self.label = QtWidgets.QLabel(parent=self.centralwidget)
        self.label.setGeometry(QtCore.QRect(200, 10, 201, 41))
        self.label.setObjectName("label")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(parent=MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 586, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(parent=MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.nameEdit.setPlaceholderText(_translate("MainWindow", "Имя"))
        self.shelterEdit.setPlaceholderText(_translate("MainWindow", "Приют"))
        self.breedEdit.setPlaceholderText(_translate("MainWindow", "Порода"))
        self.ageEdit.setPlaceholderText(_translate("MainWindow", "Возраст"))
        self.add.setText(_translate("MainWindow", "Добавить"))
        self.back.setText(_translate("MainWindow", "Вернуться"))
        self.add_photo.setText(_translate("MainWindow", "Фото - Выбрать файл"))
        self.label.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\"><span style=\" font-size:16pt;\">Добавить котика</span></p></body></html>"))
