# Form implementation generated from reading ui file 'main.ui'
#
# Created by: PyQt6 UI code generator 6.8.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 539)
        MainWindow.setStyleSheet("background-color: rgb(255, 238, 226);")
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.exit = QtWidgets.QPushButton(parent=self.centralwidget)
        self.exit.setGeometry(QtCore.QRect(330, 480, 141, 23))
        self.exit.setObjectName("exit")
        self.find_cat = QtWidgets.QPushButton(parent=self.centralwidget)
        self.find_cat.setGeometry(QtCore.QRect(330, 190, 151, 21))
        self.find_cat.setObjectName("find_cat")
        self.shelter = QtWidgets.QPushButton(parent=self.centralwidget)
        self.shelter.setGeometry(QtCore.QRect(330, 220, 151, 21))
        self.shelter.setObjectName("shelter")
        self.test = QtWidgets.QPushButton(parent=self.centralwidget)
        self.test.setGeometry(QtCore.QRect(330, 250, 151, 21))
        self.test.setObjectName("test")
        self.encyclopedia = QtWidgets.QPushButton(parent=self.centralwidget)
        self.encyclopedia.setGeometry(QtCore.QRect(330, 280, 151, 21))
        self.encyclopedia.setObjectName("encyclopedia")
        self.diary = QtWidgets.QPushButton(parent=self.centralwidget)
        self.diary.setGeometry(QtCore.QRect(330, 310, 151, 21))
        self.diary.setObjectName("diary")
        self.label = QtWidgets.QLabel(parent=self.centralwidget)
        self.label.setGeometry(QtCore.QRect(30, 20, 261, 501))
        self.label.setText("")
        self.label.setPixmap(QtGui.QPixmap("main1.jpg"))
        self.label.setScaledContents(True)
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(510, 20, 261, 501))
        self.label_2.setText("")
        self.label_2.setPixmap(QtGui.QPixmap("main2.jpg"))
        self.label_2.setScaledContents(True)
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(380, 510, 47, 13))
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(340, 70, 131, 51))
        self.label_4.setObjectName("label_4")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(parent=MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(parent=MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.exit.setText(_translate("MainWindow", "Выйти из приложения"))
        self.find_cat.setText(_translate("MainWindow", "Найти котика"))
        self.shelter.setText(_translate("MainWindow", "Мы - приют"))
        self.test.setText(_translate("MainWindow", "Тест: Какой ты котик"))
        self.encyclopedia.setText(_translate("MainWindow", "Энциклопедия"))
        self.diary.setText(_translate("MainWindow", "Дневник"))
        self.label_3.setText(_translate("MainWindow", "v.1.0.0"))
        self.label_4.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\"><span style=\" font-size:14pt;\">Мы котики</span></p></body></html>"))
