# Form implementation generated from reading ui file 'diary.ui'
#
# Created by: PyQt6 UI code generator 6.8.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 503)
        MainWindow.setStyleSheet("background-color: rgb(255, 238, 226);")
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(parent=self.centralwidget)
        self.label.setGeometry(QtCore.QRect(500, 20, 261, 391))
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(20, 70, 101, 21))
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(20, 110, 101, 31))
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(20, 160, 221, 41))
        self.label_4.setObjectName("label_4")
        self.label_5 = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_5.setGeometry(QtCore.QRect(20, 220, 271, 41))
        self.label_5.setObjectName("label_5")
        self.add_photo = QtWidgets.QPushButton(parent=self.centralwidget)
        self.add_photo.setGeometry(QtCore.QRect(580, 430, 101, 21))
        self.add_photo.setObjectName("add_photo")
        self.back = QtWidgets.QPushButton(parent=self.centralwidget)
        self.back.setGeometry(QtCore.QRect(190, 430, 75, 23))
        self.back.setObjectName("back")
        self.nameEdit = QtWidgets.QTextEdit(parent=self.centralwidget)
        self.nameEdit.setGeometry(QtCore.QRect(180, 70, 281, 31))
        self.nameEdit.setObjectName("nameEdit")
        self.textEdit_2 = QtWidgets.QTextEdit(parent=self.centralwidget)
        self.textEdit_2.setGeometry(QtCore.QRect(10, 310, 451, 111))
        self.textEdit_2.setObjectName("textEdit_2")
        self.ageEdit = QtWidgets.QTextEdit(parent=self.centralwidget)
        self.ageEdit.setGeometry(QtCore.QRect(180, 110, 281, 31))
        self.ageEdit.setObjectName("ageEdit")
        self.lastEdit = QtWidgets.QTextEdit(parent=self.centralwidget)
        self.lastEdit.setGeometry(QtCore.QRect(230, 170, 231, 31))
        self.lastEdit.setObjectName("lastEdit")
        self.featureEdit = QtWidgets.QTextEdit(parent=self.centralwidget)
        self.featureEdit.setGeometry(QtCore.QRect(290, 220, 171, 31))
        self.featureEdit.setObjectName("featureEdit")
        self.label_6 = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_6.setGeometry(QtCore.QRect(160, 270, 151, 41))
        self.label_6.setObjectName("label_6")
        self.label_7 = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_7.setGeometry(QtCore.QRect(100, 10, 271, 41))
        self.label_7.setObjectName("label_7")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(parent=MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(parent=MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label.setText(_translate("MainWindow", "TextLabel"))
        self.label_2.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:12pt;\">Имя</span></p></body></html>"))
        self.label_3.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:12pt;\">Возраст</span></p></body></html>"))
        self.label_4.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:12pt;\">Последняя прививка была</span></p></body></html>"))
        self.label_5.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:12pt;\">День, когда надо сделать прививку</span></p></body></html>"))
        self.add_photo.setText(_translate("MainWindow", "Добавить фото"))
        self.back.setText(_translate("MainWindow", "Вернуться"))
        self.label_6.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\"><span style=\" font-size:14pt;\">Заметки</span></p></body></html>"))
        self.label_7.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\"><span style=\" font-size:16pt;\">Дневник моего кота</span></p></body></html>"))
