# Form implementation generated from reading ui file 'weareshelter.ui'
#
# Created by: PyQt6 UI code generator 6.8.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 430)
        MainWindow.setStyleSheet("background-color: rgb(255, 238, 226);")
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.add_cat = QtWidgets.QPushButton(parent=self.centralwidget)
        self.add_cat.setGeometry(QtCore.QRect(110, 250, 161, 31))
        self.add_cat.setObjectName("add_cat")
        self.label = QtWidgets.QLabel(parent=self.centralwidget)
        self.label.setGeometry(QtCore.QRect(370, 20, 391, 351))
        self.label.setText("")
        self.label.setPixmap(QtGui.QPixmap("weareshelter.jpg"))
        self.label.setScaledContents(True)
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(70, 130, 81, 16))
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(140, 80, 101, 21))
        self.label_3.setObjectName("label_3")
        self.back = QtWidgets.QPushButton(parent=self.centralwidget)
        self.back.setGeometry(QtCore.QRect(150, 300, 75, 23))
        self.back.setObjectName("back")
        self.label_4 = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(70, 160, 81, 21))
        self.label_4.setObjectName("label_4")
        self.label_5 = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_5.setGeometry(QtCore.QRect(70, 190, 81, 21))
        self.label_5.setObjectName("label_5")
        self.nameEdit = QtWidgets.QTextEdit(parent=self.centralwidget)
        self.nameEdit.setGeometry(QtCore.QRect(170, 130, 151, 21))
        self.nameEdit.setObjectName("nameEdit")
        self.numberEdit = QtWidgets.QTextEdit(parent=self.centralwidget)
        self.numberEdit.setGeometry(QtCore.QRect(170, 190, 151, 21))
        self.numberEdit.setObjectName("numberEdit")
        self.addressEdit = QtWidgets.QTextEdit(parent=self.centralwidget)
        self.addressEdit.setGeometry(QtCore.QRect(170, 160, 151, 21))
        self.addressEdit.setObjectName("addressEdit")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(parent=MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(parent=MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.add_cat.setText(_translate("MainWindow", "Добавить котика"))
        self.label_2.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\"><span style=\" font-size:12pt;\">Название</span></p></body></html>"))
        self.label_3.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\"><span style=\" font-size:16pt;\">О нас</span></p></body></html>"))
        self.back.setText(_translate("MainWindow", "Вернуться"))
        self.label_4.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\"><span style=\" font-size:12pt;\">Адрес</span></p></body></html>"))
        self.label_5.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\"><span style=\" font-size:12pt;\">Телефон</span></p></body></html>"))
